name: agenda_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  provider: ^6.1.5+1
  table_calendar: ^3.2.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  http: ^1.5.0
  share_plus: ^11.1.0

  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  audioplayers: ^6.0.0
  timezone: ^0.9.4

  speech_to_text: ^7.3.0
  shared_preferences: ^2.2.2
  flutter_colorpicker: ^1.0.3
  intl: ^0.20.2

  # SOLO NECESITAS ESTO PARA EL WIDGET:
  home_widget: ^0.6.0
  # workmanager: ^0.5.2  # ELIMINADO - causa conflictos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"