// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX74Ux9U9JO78xxQXrvSxfMaqOrchPebw',
    appId: '1:757529430470:web:fd01b9179aa184bfc7cac7',
    messagingSenderId: '757529430470',
    projectId: 'agenda-5eed8',
    authDomain: 'agenda-5eed8.firebaseapp.com',
    storageBucket: 'agenda-5eed8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Wi6hBpqxZeMU8UnJMSugYFipF3z0Db0',
    appId: '1:757529430470:android:bee306120cbd3a0ec7cac7',
    messagingSenderId: '757529430470',
    projectId: 'agenda-5eed8',
    storageBucket: 'agenda-5eed8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Zmd_p4Xc1Hy1jB7dA1yqAtoLqCVLwYs',
    appId: '1:757529430470:ios:959d9e1c465b1fbec7cac7',
    messagingSenderId: '757529430470',
    projectId: 'agenda-5eed8',
    storageBucket: 'agenda-5eed8.firebasestorage.app',
    iosBundleId: 'com.example.agendaAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Zmd_p4Xc1Hy1jB7dA1yqAtoLqCVLwYs',
    appId: '1:757529430470:ios:959d9e1c465b1fbec7cac7',
    messagingSenderId: '757529430470',
    projectId: 'agenda-5eed8',
    storageBucket: 'agenda-5eed8.firebasestorage.app',
    iosBundleId: 'com.example.agendaAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX74Ux9U9JO78xxQXrvSxfMaqOrchPebw',
    appId: '1:757529430470:web:344baac53327f60bc7cac7',
    messagingSenderId: '757529430470',
    projectId: 'agenda-5eed8',
    authDomain: 'agenda-5eed8.firebaseapp.com',
    storageBucket: 'agenda-5eed8.firebasestorage.app',
  );
}
